### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by KenMizz** [Subilan/Blog#1]
怎么办

**Comment by Subilan** [comment]
emmmm 其实我也是从昨天晚上开始试，一直尝试用 Nodejs 跑 WebHooks，结果惨败。多亏有了 PHP...

------

就是在 **Settings > Web Hooks** 里，可以设定一个发送 Hooks 的链接，比如 `http://localhost/webhook.php` 等，只要是能够接收、正在运行的应用程序就可以（接收一个 POST）。

然后 GitHub 会在它发送的信息里附带一个 Signature，使用特定算法解析以后，如果跟你预设的 Secret Key 一样，就会存在一个 Boolean 等于 `true`，然后借着这个 Boolean 去运行一件事情。

每当这个项目存在一个操作，例如 Wiki 的更改、Pull Request 的发布、Issue 的 Open、Branch 的删除或者单纯的 Push 操作，都可以在 Hooks 里设定，然后通过类似于这样的结构

```php
switch ($event) {
    case "ping"
        echo "pong!"
        break;
    case "push"
        shell_exec("sh ./deploy.sh");
        break;
    // ...
    default:
        echo "Unknown Event";
}
```

来完成特定事件。

## 场景

类似于这个博客，如果你想要本地修改，用 GitHub 进行版本管理，然后再用第三方主机托管后成为网站就会出现这样的顺序

本地修改后 Commit -> GitHub 接收后记录下 Commit

那么这个时候如果第三方主机需要将 GitHub 上的文件同步到本地以实现能够从网页访问，那么就必须有一个自动化的任务——自动 Pull。

最初级的办法是用 `cron`，也就是定时。只不过这个是真的很烂。然后就是用 `.git` 提供的钩子（hooks），在 `.git/hooks` 内。虽然我不知道怎么用，貌似需要 bare 仓库？

然后就是这里的办法，使用 GitHub Web Hooks！

**Comment by KenMizz** [comment]
ok

**Comment by Subilan** [comment]
Everything done, issue closed.
